# Generated by Django 3.2.18 on 2023-02-19 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='content',
            field=models.TextField(blank=True, help_text='Ingrese el contenido de la lírica', max_length=10000000000),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='files',
            field=models.FileField(blank=True, help_text='Suba el archivo en formato pdf', upload_to=''),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='front',
            field=models.ImageField(blank=True, help_text='Ingrese una imagen de portada para la lírica', upload_to=''),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Seleccione un género para esta lírica', to='homepage.Genre'),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Calificación de la lírica'),
        ),
        migrations.AlterField(
            model_name='phrases',
            name='content',
            field=models.TextField(blank=True, help_text='Ingrese el contenido de la frase', max_length=10000000000),
        ),
        migrations.AlterField(
            model_name='phrases',
            name='files',
            field=models.FileField(blank=True, help_text='Suba el archivo en formato pdf', upload_to=''),
        ),
        migrations.AlterField(
            model_name='phrases',
            name='front',
            field=models.ImageField(blank=True, help_text='Ingrese una imagen de portada para la frase', upload_to=''),
        ),
        migrations.AlterField(
            model_name='phrases',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Seleccione un género para esta frae', to='homepage.Genre'),
        ),
        migrations.AlterField(
            model_name='phrases',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Calificación de la frase'),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='content',
            field=models.TextField(blank=True, help_text='Ingrese el contenido de la poesía', max_length=10000000000),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='files',
            field=models.FileField(blank=True, help_text='Suba el archivo en formato pdf', upload_to=''),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='front',
            field=models.ImageField(blank=True, help_text='Ingrese una imagen de portada para la poesía', upload_to=''),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Seleccione un género para esta poesía', to='homepage.Genre'),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Calificación de la poesía'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='content',
            field=models.TextField(blank=True, help_text='Ingrese el contenido del relato', max_length=10000000000),
        ),
        migrations.AlterField(
            model_name='stories',
            name='files',
            field=models.FileField(blank=True, help_text='Suba el archivo en formato pdf', upload_to=''),
        ),
        migrations.AlterField(
            model_name='stories',
            name='front',
            field=models.ImageField(blank=True, help_text='Ingrese una imagen de portada para el relato', upload_to=''),
        ),
        migrations.AlterField(
            model_name='stories',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Seleccione un género para este relato', to='homepage.Genre'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Calificación del relato'),
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('playlist', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, help_text='Ingrese el contenido del escrito', max_length=10000000000)),
                ('score', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Calificación del escrito')),
                ('front', models.ImageField(blank=True, help_text='Ingrese una imagen de portada para el escrito', upload_to='')),
                ('files', models.FileField(blank=True, help_text='Suba el archivo en formato pdf', upload_to='')),
                ('last_modified', models.DateField(auto_now=True, help_text='última modificación')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.author')),
                ('genre', models.ManyToManyField(blank=True, help_text='Seleccione un género para este escrito', to='homepage.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, help_text='Ingrese el contenido del archivo', max_length=10000000000)),
                ('score', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Calificación del archivo')),
                ('front', models.ImageField(blank=True, help_text='Ingrese una imagen de portada para el archivo', upload_to='')),
                ('files', models.FileField(blank=True, help_text='Suba el archivo en formato pdf', upload_to='')),
                ('last_modified', models.DateField(auto_now=True, help_text='última modificación')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.author')),
                ('genre', models.ManyToManyField(blank=True, help_text='Seleccione un género para este archivo', to='homepage.Genre')),
            ],
        ),
    ]
